apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-deployment
  labels:
    app: debezium-connector
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connector
  template:
    metadata:
      labels:
        app: debezium-connector
    spec:
      containers:
        - name: debezium-connector
          imagePullPolicy: IfNotPresent
          image: debezium/connect:1.7
          ports:
            - containerPort: 8083
              protocol: TCP
          resources:
            limits:
              cpu: '600m'
              memory: '2048Mi'
            requests:
              cpu: '300m'
              memory: '2048Mi'
          envFrom:
            - configMapRef:
                name: debezium-configmap
