apiVersion: v1
kind: Service
metadata:
  namespace: eshop-eda
  labels:
    app: debezium-service
  name: debezium-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    name: debezium-connector