apiVersion: v1
kind: Secret
metadata:
  name: eda-secrets
  namespace: eshop-eda
type: Opaque
data:
#  Base64 decoded database url string
  DATABASE_URL: "postgres://postgres:secret@localhost:5432/postgres"
  auth: "BASIC_AUTH"
  QUARKUS_MAILGUN_API_KEY:
  USERS_SERVICE_URL:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
