apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-backend
  labels:
    app: shipment-backend
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shipment-backend
  template:
    metadata:
      labels:
        name: shipment-backend
    spec:
      containers:
      - name: shipment-backend-service
        imagePullPolicy: Always
        image: eldimious/shipment-eda-v1:latest
        ports:
          - containerPort: 3000
            protocol: TCP
            