apiVersion: v1
kind: Service
metadata:
  namespace: eshop-eda
  labels:
    app: shipment-service
  name: shipment-service
spec:
  type: NodePort
  ports:
  - port: 9999
    targetPort: 9999
    protocol: TCP
  selector:
    name: shipment-backend