apiVersion: v1
kind: Service
metadata:
  namespace: eshop-eda
  labels:
    app: payment-service
  name: payment-service
spec:
  type: NodePort
  ports:
  - port: 3333
    targetPort: 3333
    protocol: TCP
  selector:
    name: payment-backend