const ORDERS_TOPIC = 'Orders';
const ORDER_CONFIRMED_EVENT = 'OrderConfirmed';
const SHIPMENTS_TOPIC = 'Shipments';
const SHIPMENT_PREPARED_EVENT = 'ShipmentPrepared';
const SHIPMENT_SHIPPED_EVENT = 'ShipmentShipped';
const PREPERING_SHIPMENT_STATUS = 'prepering';
const OUT_FOR_SHIPMENT_STATUS = 'out_for_shipment';
const SHIPPED_SHIPMENT_STATUS = 'shipped';
const SHIPMENT_STATUSES = Object.freeze([
  PREPERING_SHIPMENT_STATUS,
  OUT_FOR_SHIPMENT_STATUS,
  SHIPPED_SHIPMENT_STATUS,
]);


module.exports = {
  ORDER_CONFIRMED_EVENT,
  ORDERS_TOPIC,
  SHIPMENTS_TOPIC,
  SHIPMENT_PREPARED_EVENT,
  SHIPMENT_STATUSES,
  PREPERING_SHIPMENT_STATUS,
  OUT_FOR_SHIPMENT_STATUS,
  SHIPPED_SHIPMENT_STATUS,
  SHIPMENT_SHIPPED_EVENT,
};
