apiVersion: v1
kind: ConfigMap
metadata:
  namespace: eshop-eda
  name: eda-configmap
data:
  BASTION_PORT: "3000"
  KAFKA_BROKERS: ""
  DEBEZIUM_HOST: ""
  USERS_SERVICE_URL: ""
  QUARKUS_MAILGUN_DOMAIN_NAME: ""
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: ""
  GROUP_ID: "1"
  CONFIG_STORAGE_TOPIC: "connect_configs"
  OFFSET_STORAGE_TOPIC: "connect_offsets"
  STATUS_STORAGE_TOPIC: "connect_status"
  USERS_CONNECTOR_JSON: ""
  ORDERS_CONNECTOR_JSON: ""
  WAREHOUSE_CONNECTOR_JSON: ""
  PAYMENTS_CONNECTOR_JSON: ""