apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app
  labels:
    app: payment-app
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment-app
  template:
    metadata:
      labels:
        name: payment-app
    spec:
      containers:
      - name: payment-eda
        imagePullPolicy: Always
        image: eldimious/payment-eda-v1:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: '200m'
            memory: '512Mi'
          requests:
            cpu: '200m'
            memory: '512Mi'
        envFrom:
        - secretRef:
            name: payments-app-secrets
            