apiVersion: v1
kind: Service
metadata:
  namespace: eshop-eda
  labels:
    app: warehouse-service
  name: warehouse-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    name: warehouse-backend