apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-app
  labels:
    app: email-app
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      name: email-app
  template:
    metadata:
      labels:
        name: email-app
    spec:
      containers:
      - name: email-eda
        imagePullPolicy: Always
        image: eldimious/email-eda-v3:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: '200m'
            memory: '512Mi'
          requests:
            cpu: '200m'
            memory: '512Mi'
        env:
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                name: eda-configmap
                key: KAFKA_BROKERS
          - name: QUARKUS_MAILGUN_DOMAIN_NAME
            valueFrom:
              configMapKeyRef:
                name: eda-configmap
                key: QUARKUS_MAILGUN_DOMAIN_NAME
          - name: QUARKUS_MAILGUN_API_KEY
            valueFrom:
              secretKeyRef:
                name: eda-secrets
                key: QUARKUS_MAILGUN_API_KEY