apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion-app
  labels:
    app: bastion
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
        - name: bastion-eda
          imagePullPolicy: Always
          image: akoufa/bastion-eda-v1:latest
          resources:
            limits:
              cpu: '300m'
              memory: '512Mi'
            requests:
              cpu: '300m'
              memory: '256Mi'
          envFrom:
            - secretRef:
                name: bastion-app-secrets
