apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-backend
  labels:
    app: order-backend
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order-backend
  template:
    metadata:
      labels:
        name: order-backend
    spec:
      containers:
      - name: order-api
        imagePullPolicy: Always
        image: eldimious/order-eda-v1:latest
        ports:
          - containerPort: 3000
            protocol: TCP
        resources:
          limits:
            cpu: '500m'
            memory: '1024Mi'
          requests:
            cpu: '500m'
            memory: '1024Mi'`
        envFrom:
        - secretRef:
            name: orders-service-secrets
            