apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
  labels:
    app: order-app
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order-app
  template:
    metadata:
      labels:
        name: order-app
    spec:
      containers:
      - name: order-eda
        imagePullPolicy: Always
        image: eldimious/order-eda-v1:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: '200m'
            memory: '512Mi'
          requests:
            cpu: '200m'
            memory: '512Mi'
        envFrom:
        - secretRef:
            name: orders-service-secrets
            