apiVersion: v1
kind: Service
metadata:
  namespace: tf-tutorial
  labels:
    app: order-service
  name: order-service
spec:
  type: NodePort
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
  selector:
    name: order-backend