version: '3.8'
services:
  postgres:
    image: postgres:13.2
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: inventory-db
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
