const SENDER_REGISTRATION_EMAIL = 'dimosthenis.botsaris@arconsis.com';
const REGISTRATION_EMAIL_SUBJECT = 'Welcome onboard!';
const ORDERS_TOPIC = 'Orders';
const ORDER_CONFIRMED_SUBJECT = 'New order confirmed';
const ORDER_CONFIRMED_EVENT_TYPE = 'OrderConfirmed';
const ORDER_CREATED_EVENT_TYPE = 'OrderCreated';
const ORDER_CREATED_SUBJECT = 'New order was placed!';
const SHIPMENTS_TOPIC = 'Shipments';
const SHIPMENT_PREPARED_EVENT_TYPE = 'ShipmentPrepared';
const SHIPMENT_PREPARED_CONFIRMED_SUBJECT = 'The order is out for shipment';


module.exports = {
  ORDERS_TOPIC,
  REGISTRATION_EMAIL_SUBJECT,
  SENDER_REGISTRATION_EMAIL,
  ORDER_CONFIRMED_EVENT_TYPE,
  ORDER_CONFIRMED_SUBJECT,
  ORDER_CREATED_EVENT_TYPE,
  ORDER_CREATED_SUBJECT,
  SHIPMENTS_TOPIC,
  SHIPMENT_PREPARED_EVENT_TYPE,
  SHIPMENT_PREPARED_CONFIRMED_SUBJECT,
};
