apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion-deployment
  labels:
    app: bastion
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
        - name: bastion-eda
          imagePullPolicy: IfNotPresent
          image: eldimious/bastion-eda:latest
          resources:
            limits:
              cpu: '300m'
              memory: '512Mi'
            requests:
              cpu: '300m'
              memory: '256Mi'
          envFrom:
            - configMapRef:
                name: bastion-configmap
