apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion-app
  labels:
    app: bastion
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
        - name: bastion-eda
          imagePullPolicy: Always
          image: eldimious/bastion-eda-v2:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: '300m'
              memory: '512Mi'
            requests:
              cpu: '300m'
              memory: '256Mi'
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: eda-configmap
                  key: BASTION_PORT
            - name: DEBEZIUM_HOST
              valueFrom:
                configMapKeyRef:
                  name: eda-configmap
                  key: DEBEZIUM_HOST
            - name: USERS_CONNECTOR_JSON
              valueFrom:
                configMapKeyRef:
                  name: eda-configmap
                  key: USERS_CONNECTOR_JSON
            - name: ORDERS_CONNECTOR_JSON
              valueFrom:
                configMapKeyRef:
                  name: eda-configmap
                  key: ORDERS_CONNECTOR_JSON
            - name: WAREHOUSE_CONNECTOR_JSON
              valueFrom:
                configMapKeyRef:
                  name: eda-configmap
                  key: WAREHOUSE_CONNECTOR_JSON
            - name: PAYMENTS_CONNECTOR_JSON
              valueFrom:
                configMapKeyRef:
                  name: eda-configmap
                  key: PAYMENTS_CONNECTOR_JSON
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: eda-secrets
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eda-secrets
                  key: POSTGRES_USER