apiVersion: v1
kind: Service
metadata:
  namespace: eshop-eda
  labels:
    app: bastion-service
  name: bastion-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    name: bastion