version: "3.8"
services:
  kafka:
    image: lensesio/box
    restart: on-failure
    ports:
      - "3030:3030"
      - "9092:9092"
      - "8081:8081"
    environment:
      SAMPLEDATA: 0
      ADV_HOST: host.docker.internal
#  Add the following value to a .env file with your license key: "https://dl.lenses.io/d/?id=<YOUR_TRIAL_LICENSE_ID>"
      EULA:
