version: '3.7'
services:
  postgres:
    image: postgres:13.2
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders-db
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~