output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "cluster_ca_certificate" {
  description = "kubectl certificate_authority."
  value       = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = var.cluster_name
}

output "bootstrap_servers" {
  value = aws_msk_cluster.kafka.bootstrap_brokers
}

output "users_connector_json" {
  value = jsonencode(replace(data.template_file.users_connector_initializer.rendered, "\n", " "))
}

output "orders_connector_json" {
  value = jsonencode(replace(data.template_file.orders_connector_initializer.rendered, "\n", " "))
}

output "warehouse_connector_json" {
  value = jsonencode(replace(data.template_file.warehouse_connector_initializer.rendered, "\n", " "))
}

output "payments_connector_json" {
  value = jsonencode(replace(data.template_file.payment_connector_initializer.rendered, "\n", " "))
}
