apiVersion: v1
kind: Service
metadata:
  namespace: eshop-eda
  labels:
    app: payment-service
  name: payment-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: payment-app