const PENDING_ORDER_STATUS = 'pending';
const VALIDATED_ORDER_STATUS = 'valid';
const OUT_OF_STOCK_STATUS = 'out_of_stock';
const PAID_ORDER_STATUS = 'paid';
const OUT_FOR_SHIPMENT_ORDER_STATUS = 'out_for_shipment';
const COMPLETED_ORDER_STATUS = 'completed';
const PAYMENT_FAILED_ORDER_STATUS = 'payment_failed';
const CANCELLED_ORDER_STATUS = 'cancelled';
const REFUNDED_ORDER_STATUS = 'refunded';

const ORDER_STATUSES = Object.freeze([
  PENDING_ORDER_STATUS,
  VALIDATED_ORDER_STATUS,
  OUT_OF_STOCK_STATUS,
  PAID_ORDER_STATUS,
  OUT_FOR_SHIPMENT_ORDER_STATUS,
  COMPLETED_ORDER_STATUS,
  PAYMENT_FAILED_ORDER_STATUS,
  CANCELLED_ORDER_STATUS,
  REFUNDED_ORDER_STATUS,
]);

// Orders Topic
const ORDER_REQUESTED_EVENT_TYPE = 'OrderRequested';
const ORDER_CREATED_EVENT_TYPE = 'OrderCreated';
const ORDER_CONFIRMED_EVENT = 'OrderConfirmed';
const ORDERS_TOPIC = 'Orders';

// PAYMENTS Topic
const PAYMENTS_TOPIC = 'Payments';
const ORDER_PAID_EVENT = 'PaymentProcessed';
const ORDER_FAILED_PAYMENT_EVENT = 'PaymentFailed';

// SHIPMENTS Topic
const SHIPMENTS_TOPIC = 'Shipments';
const SHIPMENT_PREPARED_EVENT = 'ShipmentPrepared';
const SHIPMENT_SHIPPED_EVENT = 'ShipmentShipped';

// WAREHOUSE Topic
const WAREHOUSE_TOPIC = 'Warehouse';
const WAREHOUSE_ORDER_VALIDATED_EVENT = 'OrderValidated';
const WAREHOUSE_ORDER_INVALID_EVENT = 'OrderInvalid';

module.exports = {
  PENDING_ORDER_STATUS,
  VALIDATED_ORDER_STATUS,
  OUT_OF_STOCK_STATUS,
  PAID_ORDER_STATUS,
  OUT_FOR_SHIPMENT_ORDER_STATUS,
  COMPLETED_ORDER_STATUS,
  PAYMENT_FAILED_ORDER_STATUS,
  CANCELLED_ORDER_STATUS,
  REFUNDED_ORDER_STATUS,
  ORDER_STATUSES,
  ORDERS_TOPIC,
  ORDER_REQUESTED_EVENT_TYPE,
  ORDER_CREATED_EVENT_TYPE,
  PAYMENTS_TOPIC,
  ORDER_FAILED_PAYMENT_EVENT,
  ORDER_PAID_EVENT,
  SHIPMENTS_TOPIC,
  ORDER_CONFIRMED_EVENT,
  SHIPMENT_PREPARED_EVENT,
  SHIPMENT_SHIPPED_EVENT,
  WAREHOUSE_TOPIC,
  WAREHOUSE_ORDER_VALIDATED_EVENT,
  WAREHOUSE_ORDER_INVALID_EVENT,
};
