apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-app
  labels:
    app: email-app
  namespace: eshop-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      name: email-app
  template:
    metadata:
      labels:
        name: email-app
    spec:
      containers:
      - name: email-eda
        imagePullPolicy: Always
        image: eldimious/email-eda-v1:latest
        envFrom:
        - secretRef:
            name: email-app-secrets
        resources:
          limits:
            cpu: '200m'
            memory: '512Mi'
          requests:
            cpu: '200m'
            memory: '512Mi'
        ports:
          - containerPort: 3000
            protocol: TCP       