apiVersion: v1
kind: Service
metadata:
  namespace: eshop-eda
  labels:
    app: email-service
  name: email-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: email-app