apiVersion: v1
kind: Service
metadata:
  namespace: eshop-eda
  labels:
    app: email-service
  name: email-service
spec:
  type: NodePort
  ports:
  - port: 7777
    targetPort: 7777
    protocol: TCP
  selector:
    name: email-backend